name: onnx_ffi
description: A Dart FFI-based implementation of the `onnx` package, providing native bindings to ONNX Runtime C API for high-performance ONNX model inference.

version: 1.0.0+dev.1

homepage: https://github.com/ArishSultan/onnx_dart
repository: https://github.com/ArishSultan/onnx_dart.git
issue_tracker: https://github.com/ArishSultan/onnx_dart/issues
documentation: https://github.com/ArishSultan/onnx_dart/blob/main/packages/onnx_ffi/README.md

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.7.0

dependencies:
  ffi: ^2.1.3

  onnx_platform_interface:
    path: ../onnx_platform_interface

dev_dependencies:
  ffigen: ^16.1.0
  lints: ^5.1.1
  test: ^1.25.15
