name: onnx_web
description: A web-based Dart wrapper around ONNX Runtime Web, providing ONNX model inference for browsers and web applications. This package implements the `onnx` API specifically for web environments, leveraging ONNX Runtime Web for efficient machine learning inference.
version: 1.0.0+dev.1

homepage: https://github.com/ArishSultan/onnx_dart
repository: https://github.com/ArishSultan/onnx_dart.git
issue_tracker: https://github.com/ArishSultan/onnx_dart/issues
documentation: https://github.com/ArishSultan/onnx_dart/blob/main/packages/onnx_web/README.md

platforms:
  web:

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
